pull_request_rules:
  - name: automatic merge for ImgBot pull requests
    conditions:
        - author=imgbot[bot]
        - check-success=GitGuardian Security Checks
    actions:
        merge:
            method: merge
